[workspace]
members = ["svm-featues"]

resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["448-OG <superuser@448.africa>"]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
agave-feature-set = "2.3.6"
